services:
    web_server:
        container_name: web
        image: nginx
        ports:
            - 5000:5000           
        restart: always
        volumes:
          - ${PWD}/html/:/usr/share/nginx/html/
          - ${PWD}/conf.d/:/etc/nginx/conf.d/

    backend:
        container_name: backend
        build: api/                    
        restart: always
        command: flask --app backend run --host=0.0.0.0